export const uploadStudiesFormWorkspace = 'upload-studies-form-workspace';
export const synchronizeStudiesFormWorkspace = 'synchronize-studies-form-workspace';
export const addNewRequestWorkspace = 'add-requst-form-workspace';
export const addNewProcedureStepWorkspace = 'add-procedureStep-form-workspace';
export const studiesCount = 5;
export const seriesCount = 5
export const instancesCount = 10
export const requestCount = 5;
export const procedureStepCount = 5;
export const maxUploadImageDataSize = 2000000; // 2MB